server {
    listen 80;
    # Definir o root aqui garante que try_files sempre o encontre
    root /usr/share/nginx/html; 
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

#forcepipeline
