apiVersion: apps/v1
kind: Deployment
metadata:
  name: draco-finance
  namespace: draco-finance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draco-finance
  template:
    metadata:
      labels:
        app: draco-finance
    spec:
      containers:
      - name: draco-finance
        image: felipebg1/draco-finance:d5847fb6222b74b86f13ba7ae17aebff3fc363a7
        ports:

        - containerPort: 80
        imagePullPolicy: Always
