apiVersion: apps/v1
kind: Deployment
metadata:
  name: draco-habits
  namespace: draco-habits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draco-habits
  template:
    metadata:
      labels:
        app: draco-habits
    spec:
      containers:
      - name: draco-habits
        image: felipebg1/draco-habits:3a6c95f1fe6491b45bbd0150fb619aa24cae537c
        ports:

        - containerPort: 80
        imagePullPolicy: Always
