apiVersion: apps/v1
kind: Deployment
metadata:
  name: draco-habits
  namespace: draco-habits
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draco-habits
  template:
    metadata:
      labels:
        app: draco-habits
    spec:
      containers:
      - name: draco-habits
        image: felipebg1/draco-habits:5c0e7de203eca2644e021a06ffa2431abc068650
        ports:

        - containerPort: 80
        imagePullPolicy: Always
