apiVersion: v1
kind: Service
metadata:
  name: habits-service
  namespace: draco-habits # ADICIONE ESTA LINHA
spec:
  selector:
    app: draco-habits
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
